// KEY -> Input Template
// VAULE -> Used Info
const Assets = {
  "# Operation *": "# Operation *",
  "Object *": "Object *",
  "Make": "Make *",
  "Model": "Model Name *",
  "Part Number": "Part Number",
  "Serial Number": "Serial Number",
  "Asset Tag": "Asset ID *",
  "eAsset Tag": "eAsset Tag",
  "Name": "Name *",
  "New Name": "New Name",
  "Alias": "Alias",
  "Type": "Class *",
  "Function": "Function",
  "Customer": "Customer",
  "Status": "Status",
  "Planned Decomm. Date": "Planned Decomm. Date",
  "Is Archived": "Is Archived",
  "Location": "Location *",
  "New Location": "New Location",
  "Location Reference": "Location Reference",
  "Cabinet": "Cabinet **",
  "U Position": "U Position **",
  "Rails Used": "Rails Used **",
  "Orientation": "Orientation **",
  "Planning Date": "Planning Date",
  "Contact": "Contact",
  "Contact Team": "Contact Team",
  "Project Number": "Project Number",
  "PO Number": "PO Number",
  "Purchase Price": "Purchase Price",
  "Purchase Date": "Purchase Date",
  "Installation Date": "Installation Date",
  "SLA Profile": "SLA Profile",
  "Contract Number": "Contract Number",
  "Contract Amount": "Contract Amount",
  "Contract Start Date": "Contract Start Date",
  "Contract End Date": "Contract End Date",
  "Created On": "Created On",
  "Last Updated On": "Last Updated On",
  "Created By": "Created By",
  "Last Updated By": "Last Updated By",
  "Notes": "Notes",
};

const AssetsAddRemove = {
  "Part Number": "Part Number",
  "Serial Number": "Serial Number",
  "eAsset Tag": "eAsset Tag",
  "New Name": "New Name",
  "Alias": "Alias",
  "Function": "Function",
  "Customer": "Customer",
  "Planned Decomm. Date": "Planned Decomm. Date",
  "Is Archived": "Is Archived",
  "New Location": "New Location",
  "Location Reference": "Location Reference",
  "Planning Date": "Planning Date",
  "Contact": "Contact",
  "Contact Team": "Contact Team",
  "Project Number": "Project Number",
  "PO Number": "PO Number",
  "Purchase Price": "Purchase Price",
  "Purchase Date": "Purchase Date",
  "Installation Date": "Installation Date",
  "SLA Profile": "SLA Profile",
  "Contract Number": "Contract Number",
  "Contract Amount": "Contract Amount",
  "Contract Start Date": "Contract Start Date",
  "Contract End Date": "Contract End Date",
  "Created On": "Created On",
  "Last Updated On": "Last Updated On",
  "Created By": "Created By",
  "Last Updated By": "Last Updated By",
  "Notes": "Notes",
};

export { Assets, AssetsAddRemove };
